#!/bin/bash
if [[ $# -ne 2 ]]; then
	echo "Usage: check_avail {idle | all} {gpu | cpu}"
	echo -e "\t idle : display only idle resources"
	echo -e "\t all : display only allocated resources"
	echo -e "\t gpu : show only nodes with gres capabilities"
	echo -e "\t cpu : show only nodes without gres capabilities"
else
	echo " PARTITION AVAIL  TIMELIMIT  NODES  STATE GRES"
	if [[ $1 == idle ]]; then
		if [[ $2 == gpu ]]; then
			sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if (($5 == "idle") && ($6 != "(null)")) { print } }' -
		fi
		if [[ $2 == cpu ]]; then
			sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if (($5 == "idle") && ($6 == "(null)")) { print } }' -
		fi
	fi
	if [[ $1 == all ]]; then
		if [[ $2 == gpu ]]; then
			sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if (($5 != "idle") && ($6 != "(null)")) { print } }' -
		fi
		if [[ $2 == cpu ]]; then
			sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if (($5 != "idle") && ($6 == "(null)")) { print } }' -
		fi
	fi
fi
