#!/bin/bash
if [[ $# -ge 2 ]]; then
	echo "Usage: check_avail { | gpu | cpu}"
	echo -e "\t gpu : show only nodes with gres capabilities"
	echo -e "\t cpu : show only nodes without gres capabilities"
else
  echo ""
  echo "=================== BUSY ====================="
	echo " PARTITION AVAIL  TIMELIMIT  NODES  STATE GRES"
  case $1 in
    gpu)
      sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk 'NR>1 { if (($5 != "idle") && ($6 != "(null)")) { print } }' -
      ;;
    cpu)
      sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk 'NR>1 { if (($5 != "idle") && ($6 == "(null)")) { print } }' -
      ;;
    *)
      sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk 'NR>1 { if ($5 != "idle") { print } }' -
      ;;
  esac
  echo ""
  echo "=================== IDLE ====================="
	echo " PARTITION AVAIL  TIMELIMIT  NODES  STATE GRES"
  case $1 in
    gpu)
      sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if (($5 == "idle") && ($6 != "(null)")) { print } }' -
      ;;
    cpu)
      sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if (($5 == "idle") && ($6 == "(null)")) { print } }' -
      ;;
    *)
      sinfo -o "%.10P %.5a %.10l %.6D %.6t %G" | awk '{ if ($5 == "idle") { print } }' -
      ;;
  esac
fi
